### ISSUE TITLE
[mostly fixed] figure out how to spawn headlessly

### ISSUE THREAD

**Issue by max-mapper** [maxogden/linux#3]
to reproduce:

```
cd linux/
npm link
sudo linux boot
```

that should print 'Linux is booting' plus some data including a hostname. it also created a folder `./linux` with some files in it including an rsa keypair

now run `head /var/db/dhcpd_leases`, the top one should match the hostname above. grab the ip and try to ssh in:

```
ssh tc@<ip> -i linux/id_rsa
```

**heres the problem:** instead of logging in, it prompts for a password

however if you run `xhyve` yourself (e.g. print out the command and run it with `sudo` directly in your terminal https://github.com/maxogden/linux/commit/c1bb6cd5d243575a7494b07aa9db5bee6b1790f3) then using the same method to ssh in from another terminal works

what's different about the way we're spawning xhyve from node that makes ssh not work?

**Comment by max-mapper** [comment]
opened upstream issue here https://github.com/mafintosh/npm-execspawn/issues/3

I have fixed this for now by using normal `child_process` but keeping this open to track the upstream bug

**Comment by mafintosh** [comment]
fixed in master
