### ISSUE TITLE
can't ssh fully requires password

### ISSUE THREAD

**Issue by YonasBerhe** [maxogden/linux#7]
Why does it require a password?

**Comment by pose** [comment]
@YonasBerhe have you tried `ssh-add ./linux/id_rsa`? Then after the key is added, `ssh tc@<host ip>`

**Comment by pose** [comment]
Also, just discovered a typo in the readme: It should be `linux ssh`

**Comment by pose** [comment]
Or you can try with `linux ssh`

**Comment by YonasBerhe** [comment]
nice thx

**Comment by max-mapper** [comment]
@pose thanks for helping, @YonasBerhe glad you got it working

**Comment by pose** [comment]
@maxogden thanks to you for putting this all together, works like a charm!
