### ISSUE TITLE
Error: Timed out waiting for linux to boot

### ISSUE THREAD

**Issue by kevinsimper** [maxogden/linux#8]
Error: Timed out waiting for linux to boot

`$ linux init`

```
$ linux boot
Error: Timed out waiting for linux to boot
```

Version of xhyve that i have compiled from https://github.com/mist64/xhyve

```
$ xhyve -v
xhyve: v0.2.0
```

Version of virtualbox
![image](https://cloud.githubusercontent.com/assets/1126497/9803770/75216fbc-5826-11e5-819c-d5085be83e35.png)

Running mac os x version 10.10.5. I have rebooted as well.

**Comment by max-mapper** [comment]
@kevinsimper Heya, here are some commands you can try:
- make sure you kill the process first, `sudo linux kill`
- ensure there are no rogue xhyve processes running: `ps -fe | grep xhyve`
- if there are, kill them
- run `sudo linux boot` again. If it fails again, check `linux/stderr.log` and `linux/stdout.log` for errors
- run `cat /var/db/dhcpd_leases` and see if there is an entry with a `name` that matches the value of `linux/hostname`. This is the thing that `linux boot` waits to see  (and times out if it doesn't see it within 15 seconds)
- if you do see an entry, take the ip address and try logging in directly:

```
ssh tc@<ip> -i linux/id_rsa
```

**Comment by kevinsimper** [comment]
I did not have any rogue xhyve processes, but something with permissions. Should have looked inside the `./linux` folder.

Here is the errors that shows the denied permission

```
$ cat ./linux/stderr.log
Error return from kevent change: Invalid argument
Error return from kevent change: No such file or directory
Error return from kevent change: No such file or directory
Error return from kevent change: No such file or directory
$ cat ./linux/stdout.log
virtio_net: Could not create vmnet interface, permission denied or no entitlement?
virtio_net: Could not create vmnet interface, permission denied or no entitlement?
```

**Comment by max-mapper** [comment]
@kevinsimper the `stderr.log` looks normal (I get that output too), the `stdout.log` looks suspect, I have seen that happen sometimes when I kill an xhyve process and then run another one, sometimes I get that `vmnet interface` error the first time I try and run it, but running it a second time has fixed it every time for me. 

For `linux boot` you have to use `sudo` to enable the virtual networking in xhyve, as it creates a virtual network device on OS X. There's a check in the code that is supposed to error if you aren't running it as `uid 0`, https://github.com/maxogden/linux/blob/master/cli.js#L55-L56, so I wonder why you didn't get that error message...

**Comment by kevinsimper** [comment]
That code is 6 hours old :joy: I had 2.0.1 which was 21 hours old. 

The time it took me from installing it and updating virtual machine afterwards, I was slower than you! :joy: 

Thank you for fixing this issue so fast! 

You need to implement `linux -v` if you continue that speed!

**Comment by max-mapper** [comment]
lol
